name: netgent
runtime:
  name: python
  options:
    virtualenv: venv
description: Infrastructure for the Netgent project
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2
